### ISSUE TITLE
Not an issue but a question re time periods

### ISSUE THREAD

**Issue by DaTrader** [elixir-cldr/cldr_calendars#11]
Hey Kip,

looking at the API over and over again, I can't seem to find a way to format a duration (a time period) regardless of when it starts or ends e.g.:

2 days
3 weeks
2 quarters

Can you help with this one?

Thanks,

Damir

**Comment by kipcole9** [comment]
There is a a solution for days and weeks, but not quarters. It requires using the [ex_cldr_units](https://hex.pm/packages/ex_cldr_units) library.

```elixir
iex> days = Cldr.Unit.new!(:day, 2)
#Cldr.Unit<:day, 2>
iex> MyApp.Cldr.Unit.to_string days
{:ok, "2 days"}

iex> weeks = Cldr.Unit.new!(:week, 2)
#Cldr.Unit<:week, 2>
iex> MyApp.Cldr.Unit.to_string weeks 
{:ok, "2 weeks"}
iex> MyApp.Cldr.Unit.to_string weeks, locale: "fr"
{:ok, "2 semaines"}
iex> MyApp.Cldr.Unit.to_string weeks, locale: "de"
{:ok, "2 Wochen"}
iex> MyApp.Cldr.Unit.to_string weeks, locale: "he"
{:ok, "שבועיים"}
```

I have opened [this issue](https://unicode-org.atlassian.net/jira/software/c/projects/CLDR/issues/CLDR-15244) to add a `quarter` unit type on [CLDR](https://cldr.unicode.org) but that's not likely to happen quickly.

There may be a way to format quarters using [ex_cldr_messages](https://hex.pm/packages/ex_cldr_messages) or perhaps [gettext](https://hex.pm/packages/gettext). I'll have to think on that a bit.
