### ISSUE TITLE
Spec for `Calendar.localize/2` and `Calendar.localize/3` are conflicting 

### ISSUE THREAD

**Issue by alappe** [elixir-cldr/cldr_calendars#15]
Hello Kip,

I'm using `Cldr.Calendar.localize(month.first, :month)` and  dialyzer complains:

```
The function call will not succeed.

Cldr.Calendar.localize(any(), :month)

breaks the contract
(Date.t(), Keyword.t()) ::
  {:ok, Date.t()} | {:error, :incompatible_calendars} | {:error, {module(), String.t()}}
```

I'm not sure how to solve this. For now, I pass `[]` as the third argument to make it clear which function is used. Wanted to report it though…

Thanks for your efforts!
Andreas

- elixir v1.14.1 (OTP 25)
- dialyxir v1.2.0

**Comment by kipcole9** [comment]
My sincere apologies for how long this has taken to fix. In truth, I lose track of this issue still being open. I need to find a way to get a daily feed of open issues on my repos.

I've published [ex_cldr_calendars version 1.23.1](https://hex.pm/packages/ex_cldr_calendars/1.23.1) with the following changelog entry:

### Bug Fixes

* `Cldr.Calendar.plus/4` consistently applies a default for the `:coerce` option to `Cldr.Calendar.plus/4` and `Cldr.Calendar.minus/4`. The default is `true`. Previously the default for plus/minus months was `true` but the default for years was `false`. Thanks to @linusdm for raising the issue.

* Fix specs for `Cldr.Calendar.localize/{1..3}`. Thanks to @alappe for raising the issue. Closes #15.
