### ISSUE TITLE
Date range compare: CondClauseError

### ISSUE THREAD

**Issue by ArthurClemens** [elixir-cldr/cldr_calendars#22]
I am getting a "no match" error with these compare ranges:
```elixir
iex> Cldr.Calendar.Interval.compare(Date.range(~D[2024-09-11], ~D[2300-01-01]), Date.range(~D[2024-09-09], ~D[2024-09-11]))
```

```bash
** (CondClauseError) no cond clause evaluated to a truthy value
    (ex_cldr_calendars 1.26.1) lib/cldr/calendar/interval.ex:380: Cldr.Calendar.Interval.compare/2
```

**Comment by kipcole9** [comment]
Thanks for the report and sorry for the inconvenience. One of those "off by one" errors. I believe this is now fixed and I added additional test cases. Would you mind trying the updated code?  Just configure `{:ex_cldr_calendars, github: "elixir-cldr/cldr_calendars"}`.

I'll publish an update to hex if its all ok on your app.

**Comment by ArthurClemens** [comment]
Yes, the problem is fixed.
