### ISSUE TITLE
Type violation on Duration when compiled on Elixir 1.18.1

### ISSUE THREAD

**Issue by tjchambers** [elixir-cldr/cldr_calendars#23]
```elixir
     warning: the following clause will never match:

         {:error, {exception, reason}}

     because it attempts to match on the result of:

         to_string(duration, options)

     which has type:

         dynamic({:ok, term()})

     typing violation found at:
     │
 202 │       {:error, {exception, reason}} -> raise exception, reason
     │       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     │
     └─ lib/cldr/calendar/duration.ex:202: Cldr.Calendar.Duration.to_string!/2
 ```

**Comment by kipcole9** [comment]
THanks @tjchambers. Curiously I don't get that same type warning on my dev machines (I do get two other type warnings though - my first ones!).  I agree with the warning above and I'll fix the code now. But I'm curious why I'm not seeing the warning thought. And why you aren't seeing the two warnings I am seeing.

**Comment by tjchambers** [comment]
That is interesting...

My setup:

Erlang/OTP 27 [erts-15.0] [source] [64-bit] [smp:24:24] [ds:24:24:10] [async-threads:1] [jit]

Elixir 1.18.1 (compiled with Erlang/OTP 27)

**Comment by kipcole9** [comment]
If I configure `ex_cldr_calendars` as a dependency then I see that typing warning. If I just compile the lib itself (not as a dependency) I do not.

And conversely, I don't see the two other typing warnings when configured as a dependency and I do when I compile the lib standalone.

I'll fix all the warnings but it seems strange to have different behaviour depending on whether the code is a dependency or not.

**Comment by tjchambers** [comment]
Definitely agree. Worth understanding re: set-theoretic type checking.

**Comment by kipcole9** [comment]
> And conversely, I don't see the two other typing warnings when configured as a dependency and I do when I compile the lib standalone.

This was due to misconfiguration of some test calendars. Which fully explains the behaviour I was seeing that you were not. False alarm.

I will make a reproducible case for your warning not appearing when compiling the lib standalone.

**Comment by kipcole9** [comment]
I've published [ex_cldr_calendars version 1.26.3](https://hex.pm/packages/ex_cldr_calendars/1.26.3) with the filling changelog entry:

### Bug Fixes

* Fix typing warning on Elixir 1.18. Thanks to @tjchambers for the report. Closes #23.

**Comment by kipcole9** [comment]
Just FYI, the reason for all of this is that `Cldr.Calendar.Duration.to_string/2` has two implementations of which one is selected at compile time based upon whether or not `ex_cldr_units` is also configured.

I will publish another bug fix release resolving this more cleanly and fixing the other warnings. Sorry for the premature release.

**Comment by tjchambers** [comment]
Thanks for helping me understand it, and again thanks for jumping on this so quickly given it is "just" a warning. 

You are an outstanding example of an OSS maintainer and a gift to the Elixir community. Above and beyond.
