### ISSUE TITLE
Compile error on master with backend.Cldr.get_locale/0

### ISSUE THREAD

**Issue by dbernheisel** [elixir-cldr/cldr_calendars#5]
Looks like [this commit](https://github.com/elixir-cldr/cldr_calendars/commit/179f791c5300dfaae60fc0362dbca029e359a729) makes compilation circular?

<details>
<summary>Here's what I have:</summary>

```elixir
# mix.exs
def deps() do
  # ...
  {:ex_cldr, github: "elixir-cldr/cldr", override: true},
  {:ex_cldr_calendars, github: "elixir-cldr/cldr_calendars", override: true},
  {:ex_cldr_calendars_format, github: "elixir-cldr/cldr_calendars_format", override: true},
  {:cldr_utils, github: "elixir-cldr/cldr_utils", override: true}, # Remove once off of cldr master
  # ...
end

# lib/my_app/cldr.ex
defmodule MyApp.Cldr do
  @moduledoc """
  Internationalization support for MyApp
  """

  use Cldr,
    otp_app: :my_app,
    providers: [Cldr.Calendar, Cldr.DateTime, Cldr.Number, Cldr.Unit]

end

# lib/my_app/cldr_calendars.ex
defmodule MyApp.Calendar.US do
  @moduledoc """
  This is the same as a regular Calendar, but with Sunday starting the week.
  """

  use Cldr.Calendar.Base.Month,
    month_of_year: 1,
    min_days_in_first_week: 1,
    day_of_week: Cldr.Calendar.sunday(),
    cldr_backend: MyApp.Cldr

end
```
</details>

Here's the error
```console
$ mix deps.clean ex_cldr_calendars ex_cldr ex_cldr_calendars_format cldr_utils
$ mix deps.get
$ mix compile
==> ex_cldr_calendars
Compiling 20 files (.ex)

== Compilation error in file lib/cldr/calendar/calendars/iso_week.ex ==
** (UndefinedFunctionError) function MyApp.Cldr.get_locale/0 is undefined (module MyApp.Cldr is not available)
    MyApp.Cldr.get_locale()
    lib/cldr/calendar/config.ex:79: Cldr.Calendar.Config.extract_options/1
    expanding macro: Cldr.Calendar.Compiler.Week.__before_compile__/1
    lib/cldr/calendar/calendars/iso_week.ex:3: Cldr.Calendar.ISOWeek (module)
could not compile dependency :ex_cldr_calendars, "mix compile" failed. You can recompile this dependency with "mix deps.compile
 ex_cldr_calendars", update it with "mix deps.update ex_cldr_calendars" or clean it with "mix deps.clean ex_cldr_calendars"
```

I've also deleted `./_build` and re-compiled but same result.

The [prior commit](https://github.com/elixir-cldr/cldr_calendars/commit/c1265523f48aaf51d53eba105ae1c0666b71c144) compiles without issue.

**Comment by kipcole9** [comment]
I swap between machines for development and push work-in-progress to GitHub to keep both all machines up-to-date. Which unfortunately means that sometimes `master` isn't in a coherent state.

Anyway, I have pushed a new commit that tests cleanly so hopefully you'll be back in business.  Sorry for the inconvenience. Let me know if this puts you back in business?

**Comment by dbernheisel** [comment]
Tried on a different machine, pulled down last master and still has the same issue. I'll start a new barebones project and see if I can reproduce there and push it up.

**Comment by kipcole9** [comment]
I admire your bravery :-)

This `master` branch relies on a bunch of development versions of dependent libs, including `ex_cldr` which is a big repo (but a much smaller hex package). I think if you can hold off for a couple of weeks it might save your sanity.

If you are keen enough to work this through, you'll need to clone [cldr](httpsL//github.com/elixir-cldr/cldr) into a directory at the same level as your test lib. Is that something you've done?  I think the rest should work without further effort.

I'll also create a dummy app and try it out within the next hour.

**Comment by dbernheisel** [comment]
I was able to reproduce here: https://github.com/dbernheisel/ex_cldr_setup. I pointed the deps cldr and cldr_utils to the github repo and a copy of the repo pulled locally; both resulted in the same error.

**Comment by kipcole9** [comment]
Appreciate the support a lot, thanks.

I know the source of the error and will fix in the next commit. About 20 minutes from now.

**Comment by dbernheisel** [comment]
Thanks! Verified it fixes my small repo.
